
package br.com.produtos.webservice.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CadastrarProdutos", targetNamespace = "http://webservice.produtos.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CadastrarProdutos {


    /**
     * 
     * @param valor
     * @param nome
     */
    @WebMethod
    @RequestWrapper(localName = "newProduto", targetNamespace = "http://webservice.produtos.com.br/", className = "br.com.produtos.webservice.cliente.NewProduto")
    @ResponseWrapper(localName = "newProdutoResponse", targetNamespace = "http://webservice.produtos.com.br/", className = "br.com.produtos.webservice.cliente.NewProdutoResponse")
    @Action(input = "http://webservice.produtos.com.br/CadastrarProdutos/newProdutoRequest", output = "http://webservice.produtos.com.br/CadastrarProdutos/newProdutoResponse")
    public void newProduto(
        @WebParam(name = "nome", targetNamespace = "")
        String nome,
        @WebParam(name = "valor", targetNamespace = "")
        Double valor);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProdutos", targetNamespace = "http://webservice.produtos.com.br/", className = "br.com.produtos.webservice.cliente.GetProdutos")
    @ResponseWrapper(localName = "getProdutosResponse", targetNamespace = "http://webservice.produtos.com.br/", className = "br.com.produtos.webservice.cliente.GetProdutosResponse")
    @Action(input = "http://webservice.produtos.com.br/CadastrarProdutos/getProdutosRequest", output = "http://webservice.produtos.com.br/CadastrarProdutos/getProdutosResponse")
    public String getProdutos();

}
